mutation LoginWithGoogle($idToken: String!) {
    loginWithGoogle(idToken: $idToken) {
        accessToken
        refreshToken
        hasOnBoarded
        userId
    }
}

mutation DevLogin($email: String!) {
    devLogin(email: $email) {
        accessToken
        refreshToken
        hasOnBoarded
        userId
    }
}

mutation Refresh($refreshToken: String!){
    refresh(refreshToken: $refreshToken){
        accessToken
        refreshToken
        hasOnBoarded
        userId
    }
}

mutation Logout{
    logout
}
