import { StyleSheet } from '@react-pdf/renderer';

export const gamesStyles = StyleSheet.create({
  gameCard: {
    borderWidth: 1,
    borderColor: '#374151',
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    backgroundColor: '#111827',
    break: 'avoid',
  },
  gameHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  dateText: {
    fontSize: 9,
    color: '#9ca3af',
    flex: 1,
  },
  label: {
    fontSize: 8,
    color: '#fdba74',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  icon: {
    fontSize: 12,
    marginRight: 6,
    color: '#374151',
  },
  scoreBoard: {
    borderRadius: 12,
    backgroundColor: '#030712',
    borderWidth: 1,
    borderColor: '#1f2937',
    paddingVertical: 14,
    paddingHorizontal: 10,
    marginBottom: 12,
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  teamName: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#ffffff',
    width: '30%',
    textAlign: 'right',
    paddingRight: 8,
  },
  scoreValue: {
    fontSize: 34,
    fontWeight: 'bold',
    color: '#ffffff',
    width: '20%',
    textAlign: 'center',
  },
  teamScoreValue: {
    color: '#fb923c',
  },
  dash: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#4b5563',
    width: '10%',
    textAlign: 'center',
  },
  opponentName: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#ffffff',
    width: '30%',
    textAlign: 'left',
    paddingLeft: 8,
  },
  boxScoreHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#fb923c',
    paddingVertical: 6,
    marginTop: 6,
    backgroundColor: '#1f2937',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  boxScoreRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderColor: '#374151',
    paddingVertical: 5,
  },
  cell: {
    fontSize: 9,
    color: '#e5e7eb',
    flex: 1,
    textAlign: 'center',
  },
  playerName: {
    textAlign: 'left',
    paddingLeft: 4,
    flex: 2,
  },
});
