mutation DeleteGamePlan($input: DeleteGamePlanInput!) {
  deleteGamePlan(input: $input) {
    id
    name
    opponent
    notes
    activityId
    teamId
    createdAt
    updatedAt
    activity {
      id
      title
      date
      time
    }
    plays {
      id
      name
      category
    }
  }
}
