/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "query GetUser($teamShortId: String!) {\n  getCurrentUser(teamShortId: $teamShortId) {\n    user {\n      id\n      name\n      email\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    member {\n      id\n      userId\n      teamId\n      role\n      status\n      number\n      position\n      attendances {\n        id\n        activityId\n        memberId\n        attendanceStatus\n        reason\n        createdAt\n        updatedAt\n        activity {\n          id\n          title\n          time\n          date\n        }\n      }\n    }\n  }\n}": typeof types.GetUserDocument,
    "mutation createTeam($input: CreateTeamInput!) {\n  createTeam(input: $input) {\n    id\n    name\n    image\n    ageGroup\n    code\n    creatorId\n  }\n}": typeof types.CreateTeamDocument,
    "mutation Login($email: String!) {\n  login(email: $email) {\n    accessToken\n    refreshToken\n    hasOnBoarded\n    userId\n  }\n}\n\nmutation Refresh($refreshToken: String!) {\n  refresh(refreshToken: $refreshToken) {\n    accessToken\n    refreshToken\n    hasOnBoarded\n    userId\n  }\n}\n\nmutation Logout {\n  logout\n}": typeof types.LoginDocument,
    "mutation SubmitAttendance($input: PlayerActivityAttendanceInput!) {\n  submitAttendance(input: $input) {\n    id\n    memberId\n    attendanceStatus\n    reason\n  }\n}": typeof types.SubmitAttendanceDocument,
    "mutation AcceptTeamRequest($input: AcceptTeamRequestInput!) {\n  acceptTeamRequest(input: $input) {\n    memberId\n    teamId\n    status\n  }\n}": typeof types.AcceptTeamRequestDocument,
    "mutation JoinTeam($input: JoinTeamInput!) {\n  joinTeam(input: $input) {\n    teamCode\n    position\n    number\n  }\n}": typeof types.JoinTeamDocument,
    "mutation RejectJoinRequest($input: TeamRequestInput!) {\n  rejectJoinRequest(input: $input) {\n    memberId\n    teamId\n    status\n  }\n}": typeof types.RejectJoinRequestDocument,
    "mutation UpdateUser($input: UpdateUserInput!) {\n  updateUser(input: $input) {\n    name\n    dateOfBirth\n    phone\n    height\n    weight\n    dominantHand\n  }\n}": typeof types.UpdateUserDocument,
    "query GetTeamForDashboard {\n  getDashboardTeams {\n    id\n    name\n    slug\n    shortId\n    routeKey\n    ageGroup\n    members {\n      id\n    }\n    activities {\n      id\n      type\n      title\n      date\n      time\n    }\n  }\n}": typeof types.GetTeamForDashboardDocument,
    "mutation CreateGamePlan($input: CreateGamePlanInput!) {\n  createGamePlan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": typeof types.CreateGamePlanDocument,
    "mutation CreatePlay($input: CreatePlayInput!) {\n  createPlay(input: $input) {\n    id\n    routeKey\n    name\n    description\n    category\n    canvas\n    createdAt\n    updatedAt\n  }\n}": typeof types.CreatePlayDocument,
    "mutation CreatePracticePreparation($input: CreatePracticePreparationInput!) {\n  createPracticePreparation(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": typeof types.CreatePracticePreparationDocument,
    "mutation DeleteGamePlan($input: DeleteGamePlanInput!) {\n  deleteGamePlan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": typeof types.DeleteGamePlanDocument,
    "mutation DeletePlay($input: DeletePlayInput!) {\n  deletePlay(input: $input)\n}": typeof types.DeletePlayDocument,
    "mutation DeletePracticePreparation($input: DeletePracticePreparationInput!) {\n  deletePracticePreparation(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": typeof types.DeletePracticePreparationDocument,
    "query GetGameplan($input: GetGamePlansInput!) {\n  getGameplan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": typeof types.GetGameplanDocument,
    "query GetGameplanById($input: GetGamePlanByIdInput!) {\n  getGameplanById(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": typeof types.GetGameplanByIdDocument,
    "query GetGames($input: GetActivitiesInput!) {\n  getGames(input: $input) {\n    id\n    date\n    time\n    game {\n      id\n      title\n      date\n      time\n      activityId\n      location\n      opponentStatline {\n        activityId\n        name\n        fieldGoalsMade\n        threePointersMade\n        freeThrowsMade\n      }\n    }\n  }\n}": typeof types.GetGamesDocument,
    "query GetPlay($input: GetPlayInput!) {\n  getPlay(input: $input) {\n    id\n    routeKey\n    name\n    category\n    description\n    canvas\n    createdAt\n    updatedAt\n  }\n}": typeof types.GetPlayDocument,
    "query GetPlays($input: GetPlaysInput!) {\n  getPlays(input: $input) {\n    id\n    routeKey\n    name\n    category\n    description\n    canvas\n    createdAt\n    updatedAt\n  }\n}": typeof types.GetPlaysDocument,
    "query GetPracticePreparationById($input: GetPracticePreparationByIdInput!) {\n  getPracticePreparationById(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": typeof types.GetPracticePreparationByIdDocument,
    "query GetPracticePreparations($input: GetPracticePreparationsInput!) {\n  getPracticePreparations(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": typeof types.GetPracticePreparationsDocument,
    "query GetPractices($input: GetActivitiesInput!) {\n  getPractices(input: $input) {\n    practice {\n      id\n      title\n      date\n      time\n      activityId\n      facility\n      practicetype\n    }\n  }\n}": typeof types.GetPracticesDocument,
    "query GetTeamActivities($routeKey: String!) {\n  getTeamActivities(routeKey: $routeKey) {\n    id\n    name\n    code\n    slug\n    routeKey\n    shortId\n    image\n    ageGroup\n    createdAt\n    updatedAt\n    creatorId\n    members {\n      id\n      name\n      image\n      teamId\n      userId\n    }\n    activities {\n      id\n      teamId\n      type\n      title\n      time\n      duration\n      date\n      createdAt\n      updatedAt\n      attendees {\n        id\n        activityId\n        memberId\n        attendanceStatus\n        reason\n        createdAt\n        updatedAt\n      }\n    }\n  }\n}": typeof types.GetTeamActivitiesDocument,
    "mutation CreateFeedback($input: CreateFeedbackInput!) {\n  createFeedback(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    feedback {\n      notes\n      coach\n    }\n  }\n}": typeof types.CreateFeedbackDocument,
    "mutation CreateFilm($input: CreateFilmInput!) {\n  createFilm(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    film {\n      notes\n    }\n  }\n}": typeof types.CreateFilmDocument,
    "mutation CreateGame($input: CreateGameInput!) {\n  createGame(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    game {\n      location\n    }\n  }\n}": typeof types.CreateGameDocument,
    "mutation CreateMeeting($input: CreateMeetingInput!) {\n  createMeeting(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    meeting {\n      notes\n    }\n  }\n}": typeof types.CreateMeetingDocument,
    "mutation CreatePractice($input: CreatePracticeInput!) {\n  createPractice(input: $input) {\n    title\n    time\n    date\n    duration\n    type\n    practice {\n      facility\n      practicetype\n    }\n  }\n}": typeof types.CreatePracticeDocument,
    "mutation DeleteActivity($input: DeleteActivity!) {\n  deleteActivity(input: $input) {\n    id\n  }\n}": typeof types.DeleteActivityDocument,
    "mutation UpdateFeedback($input: UpdateFeedbackInput!) {\n  updateFeedback(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    teamId\n    feedback {\n      notes\n      coach\n    }\n  }\n}": typeof types.UpdateFeedbackDocument,
    "mutation UpdateFilm($input: UpdateFilmInput!) {\n  updateFilm(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    teamId\n    film {\n      notes\n    }\n  }\n}": typeof types.UpdateFilmDocument,
    "mutation UpdateGame($input: UpdateGameInput!) {\n  updateGame(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    game {\n      location\n    }\n  }\n}": typeof types.UpdateGameDocument,
    "mutation UpdateMeeting($input: UpdateMeetingInput!) {\n  updateMeeting(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    meeting {\n      notes\n    }\n  }\n}": typeof types.UpdateMeetingDocument,
    "mutation UpdatePractice($input: UpdatePracticeInput!) {\n  updatePractice(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    practice {\n      facility\n      practicetype\n    }\n  }\n}": typeof types.UpdatePracticeDocument,
    "query GetActiveAttendedMembers($input: ActiveAttendedMembersInput!) {\n  getActiveAttendedMembers(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    user {\n      id\n      name\n      image\n      email\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    statlines {\n      id\n      activityId\n      fieldGoalsMade\n      fieldGoalsMissed\n      threePointersMade\n      threePointersMissed\n      freeThrows\n      missedFreeThrows\n      assists\n      steals\n      turnovers\n      offensiveRebounds\n      defensiveRebounds\n      blocks\n    }\n  }\n}": typeof types.GetActiveAttendedMembersDocument,
    "query GetActivity($input: GetActivityInput!) {\n  getActivity(input: $input) {\n    id\n    title\n    time\n    type\n    duration\n    date\n    createdAt\n    updatedAt\n    teamId\n    attendees {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n    }\n    game {\n      activityId\n      location\n      opponentStatline {\n        activityId\n        name\n        fieldGoalsMade\n        threePointersMade\n        freeThrowsMade\n      }\n    }\n  }\n}": typeof types.GetActivityDocument,
    "query GetGamesWithBoxScores($input: TeamStatlineInput!) {\n  getGamesWithBoxScores(input: $input) {\n    activityId\n    title\n    date\n    opponentName\n    opponentStats {\n      fieldGoalsMade\n      threePointersMade\n      freeThrowsMade\n      points\n    }\n    teamTotals {\n      fieldGoalsMade\n      threePointersMade\n      freeThrows\n      assists\n      offensiveRebounds\n      defensiveRebounds\n      steals\n      blocks\n      turnovers\n      points\n    }\n    playerStats {\n      memberId\n      name\n      fieldGoalsMade\n      threePointersMade\n      freeThrows\n      assists\n      offensiveRebounds\n      defensiveRebounds\n      steals\n      blocks\n      turnovers\n      points\n    }\n  }\n}": typeof types.GetGamesWithBoxScoresDocument,
    "query GetStatlineAverages($input: TeamStatlineInput!) {\n  getStatlineAverages(input: $input) {\n    memberId\n    name\n    totalPoints\n    gamesPlayed\n    averages {\n      pointsPerGame\n      fieldGoalPercentage\n      threePointPercentage\n      freeThrowPercentage\n      assists\n      offensiveRebound\n      defensiveRebound\n      blocks\n      steals\n      turnovers\n    }\n  }\n}": typeof types.GetStatlineAveragesDocument,
    "query GetStatsPerGame($input: StatsPerGameInput!) {\n  getStatsPerGame(input: $input) {\n    gameTitle\n    date\n    points\n    assists\n    rebounds\n    steals\n  }\n}": typeof types.GetStatsPerGameDocument,
    "query GetTeamStats($input: TeamStatlineInput!) {\n  getTeamStats(input: $input) {\n    totalGames\n    totalFieldGoalsMade\n    totalFieldGoalsMissed\n    totalThreePointersMade\n    totalThreePointersMissed\n    totalFreeThrows\n    totalFreeThrowsMissed\n    totalAssists\n    totalRebounds\n    totalSteals\n    totalBlocks\n    totalTurnovers\n    totalPoints\n    totalOpponentPoints\n    averages {\n      pointsPerGame\n      fieldGoalPercentage\n      threePointPercentage\n      freeThrowPercentage\n      assists\n      rebounds\n      steals\n      blocks\n      turnovers\n    }\n    advanced {\n      offensiveRating\n      trueShootingPercentage\n      assistToTurnoverRatio\n      netRating\n      effectiveFieldGoalPercentage\n    }\n  }\n}": typeof types.GetTeamStatsDocument,
    "query GetWeeklyTeamAverages($input: TeamStatlineInput!) {\n  getWeeklyTeamAverages(input: $input) {\n    weekStart\n    gamesPlayed\n    totalPoints\n    fieldGoalsMade\n    fieldGoalsMissed\n    threePointersMade\n    threePointersMissed\n    freeThrows\n    freeThrowsMissed\n    assists\n    rebounds\n    steals\n    blocks\n    turnovers\n    averages {\n      pointsPerGame\n      assistsPerGame\n      reboundsPerGame\n      blocksPerGame\n      stealsPerGame\n      turnoversPerGame\n    }\n  }\n}": typeof types.GetWeeklyTeamAveragesDocument,
    "mutation SubmitStatlines($input: SubmitStatlinesInput!) {\n  submitStatlines(input: $input) {\n    success\n    count\n    opponentStatline {\n      gameId\n      name\n      fieldGoalsMade\n      threePointersMade\n      freeThrowsMade\n    }\n  }\n}": typeof types.SubmitStatlinesDocument,
    "mutation DeleteMember($input: DeleteMemberInput!) {\n  deleteMember(input: $input)\n}": typeof types.DeleteMemberDocument,
    "query GetMembers($input: MembersInput!) {\n  getMembers(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    attendances {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n      activity {\n        id\n        title\n        time\n        date\n      }\n    }\n    user {\n      id\n      name\n      email\n      image\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n  }\n}": typeof types.GetMembersDocument,
    "query GetTeam($input: GetTeamInput!) {\n  getTeam(input: $input) {\n    id\n    name\n    code\n    slug\n    shortId\n    routeKey\n    image\n    ageGroup\n    creatorId\n    createdAt\n    updatedAt\n    members {\n      id\n      teamId\n      name\n      number\n      position\n      image\n      user {\n        id\n        name\n        email\n        image\n        dateOfBirth\n        phone\n        height\n        weight\n        dominantHand\n        hasOnBoarded\n      }\n    }\n  }\n}": typeof types.GetTeamDocument,
    "query GetUserProfile($input: GetMemberProfileInput!) {\n  getUserProfile: getMemberProfile(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    user {\n      id\n      name\n      email\n      image\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    attendances {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n      activity {\n        id\n        title\n        time\n        date\n      }\n    }\n  }\n}": typeof types.GetUserProfileDocument,
    "query GetPendingMembers($input: MembersInput!) {\n  getPendingMembers(input: $input) {\n    id\n    name\n    email\n  }\n}": typeof types.GetPendingMembersDocument,
};
const documents: Documents = {
    "query GetUser($teamShortId: String!) {\n  getCurrentUser(teamShortId: $teamShortId) {\n    user {\n      id\n      name\n      email\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    member {\n      id\n      userId\n      teamId\n      role\n      status\n      number\n      position\n      attendances {\n        id\n        activityId\n        memberId\n        attendanceStatus\n        reason\n        createdAt\n        updatedAt\n        activity {\n          id\n          title\n          time\n          date\n        }\n      }\n    }\n  }\n}": types.GetUserDocument,
    "mutation createTeam($input: CreateTeamInput!) {\n  createTeam(input: $input) {\n    id\n    name\n    image\n    ageGroup\n    code\n    creatorId\n  }\n}": types.CreateTeamDocument,
    "mutation Login($email: String!) {\n  login(email: $email) {\n    accessToken\n    refreshToken\n    hasOnBoarded\n    userId\n  }\n}\n\nmutation Refresh($refreshToken: String!) {\n  refresh(refreshToken: $refreshToken) {\n    accessToken\n    refreshToken\n    hasOnBoarded\n    userId\n  }\n}\n\nmutation Logout {\n  logout\n}": types.LoginDocument,
    "mutation SubmitAttendance($input: PlayerActivityAttendanceInput!) {\n  submitAttendance(input: $input) {\n    id\n    memberId\n    attendanceStatus\n    reason\n  }\n}": types.SubmitAttendanceDocument,
    "mutation AcceptTeamRequest($input: AcceptTeamRequestInput!) {\n  acceptTeamRequest(input: $input) {\n    memberId\n    teamId\n    status\n  }\n}": types.AcceptTeamRequestDocument,
    "mutation JoinTeam($input: JoinTeamInput!) {\n  joinTeam(input: $input) {\n    teamCode\n    position\n    number\n  }\n}": types.JoinTeamDocument,
    "mutation RejectJoinRequest($input: TeamRequestInput!) {\n  rejectJoinRequest(input: $input) {\n    memberId\n    teamId\n    status\n  }\n}": types.RejectJoinRequestDocument,
    "mutation UpdateUser($input: UpdateUserInput!) {\n  updateUser(input: $input) {\n    name\n    dateOfBirth\n    phone\n    height\n    weight\n    dominantHand\n  }\n}": types.UpdateUserDocument,
    "query GetTeamForDashboard {\n  getDashboardTeams {\n    id\n    name\n    slug\n    shortId\n    routeKey\n    ageGroup\n    members {\n      id\n    }\n    activities {\n      id\n      type\n      title\n      date\n      time\n    }\n  }\n}": types.GetTeamForDashboardDocument,
    "mutation CreateGamePlan($input: CreateGamePlanInput!) {\n  createGamePlan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": types.CreateGamePlanDocument,
    "mutation CreatePlay($input: CreatePlayInput!) {\n  createPlay(input: $input) {\n    id\n    routeKey\n    name\n    description\n    category\n    canvas\n    createdAt\n    updatedAt\n  }\n}": types.CreatePlayDocument,
    "mutation CreatePracticePreparation($input: CreatePracticePreparationInput!) {\n  createPracticePreparation(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": types.CreatePracticePreparationDocument,
    "mutation DeleteGamePlan($input: DeleteGamePlanInput!) {\n  deleteGamePlan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": types.DeleteGamePlanDocument,
    "mutation DeletePlay($input: DeletePlayInput!) {\n  deletePlay(input: $input)\n}": types.DeletePlayDocument,
    "mutation DeletePracticePreparation($input: DeletePracticePreparationInput!) {\n  deletePracticePreparation(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": types.DeletePracticePreparationDocument,
    "query GetGameplan($input: GetGamePlansInput!) {\n  getGameplan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": types.GetGameplanDocument,
    "query GetGameplanById($input: GetGamePlanByIdInput!) {\n  getGameplanById(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": types.GetGameplanByIdDocument,
    "query GetGames($input: GetActivitiesInput!) {\n  getGames(input: $input) {\n    id\n    date\n    time\n    game {\n      id\n      title\n      date\n      time\n      activityId\n      location\n      opponentStatline {\n        activityId\n        name\n        fieldGoalsMade\n        threePointersMade\n        freeThrowsMade\n      }\n    }\n  }\n}": types.GetGamesDocument,
    "query GetPlay($input: GetPlayInput!) {\n  getPlay(input: $input) {\n    id\n    routeKey\n    name\n    category\n    description\n    canvas\n    createdAt\n    updatedAt\n  }\n}": types.GetPlayDocument,
    "query GetPlays($input: GetPlaysInput!) {\n  getPlays(input: $input) {\n    id\n    routeKey\n    name\n    category\n    description\n    canvas\n    createdAt\n    updatedAt\n  }\n}": types.GetPlaysDocument,
    "query GetPracticePreparationById($input: GetPracticePreparationByIdInput!) {\n  getPracticePreparationById(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": types.GetPracticePreparationByIdDocument,
    "query GetPracticePreparations($input: GetPracticePreparationsInput!) {\n  getPracticePreparations(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}": types.GetPracticePreparationsDocument,
    "query GetPractices($input: GetActivitiesInput!) {\n  getPractices(input: $input) {\n    practice {\n      id\n      title\n      date\n      time\n      activityId\n      facility\n      practicetype\n    }\n  }\n}": types.GetPracticesDocument,
    "query GetTeamActivities($routeKey: String!) {\n  getTeamActivities(routeKey: $routeKey) {\n    id\n    name\n    code\n    slug\n    routeKey\n    shortId\n    image\n    ageGroup\n    createdAt\n    updatedAt\n    creatorId\n    members {\n      id\n      name\n      image\n      teamId\n      userId\n    }\n    activities {\n      id\n      teamId\n      type\n      title\n      time\n      duration\n      date\n      createdAt\n      updatedAt\n      attendees {\n        id\n        activityId\n        memberId\n        attendanceStatus\n        reason\n        createdAt\n        updatedAt\n      }\n    }\n  }\n}": types.GetTeamActivitiesDocument,
    "mutation CreateFeedback($input: CreateFeedbackInput!) {\n  createFeedback(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    feedback {\n      notes\n      coach\n    }\n  }\n}": types.CreateFeedbackDocument,
    "mutation CreateFilm($input: CreateFilmInput!) {\n  createFilm(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    film {\n      notes\n    }\n  }\n}": types.CreateFilmDocument,
    "mutation CreateGame($input: CreateGameInput!) {\n  createGame(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    game {\n      location\n    }\n  }\n}": types.CreateGameDocument,
    "mutation CreateMeeting($input: CreateMeetingInput!) {\n  createMeeting(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    meeting {\n      notes\n    }\n  }\n}": types.CreateMeetingDocument,
    "mutation CreatePractice($input: CreatePracticeInput!) {\n  createPractice(input: $input) {\n    title\n    time\n    date\n    duration\n    type\n    practice {\n      facility\n      practicetype\n    }\n  }\n}": types.CreatePracticeDocument,
    "mutation DeleteActivity($input: DeleteActivity!) {\n  deleteActivity(input: $input) {\n    id\n  }\n}": types.DeleteActivityDocument,
    "mutation UpdateFeedback($input: UpdateFeedbackInput!) {\n  updateFeedback(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    teamId\n    feedback {\n      notes\n      coach\n    }\n  }\n}": types.UpdateFeedbackDocument,
    "mutation UpdateFilm($input: UpdateFilmInput!) {\n  updateFilm(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    teamId\n    film {\n      notes\n    }\n  }\n}": types.UpdateFilmDocument,
    "mutation UpdateGame($input: UpdateGameInput!) {\n  updateGame(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    game {\n      location\n    }\n  }\n}": types.UpdateGameDocument,
    "mutation UpdateMeeting($input: UpdateMeetingInput!) {\n  updateMeeting(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    meeting {\n      notes\n    }\n  }\n}": types.UpdateMeetingDocument,
    "mutation UpdatePractice($input: UpdatePracticeInput!) {\n  updatePractice(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    practice {\n      facility\n      practicetype\n    }\n  }\n}": types.UpdatePracticeDocument,
    "query GetActiveAttendedMembers($input: ActiveAttendedMembersInput!) {\n  getActiveAttendedMembers(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    user {\n      id\n      name\n      image\n      email\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    statlines {\n      id\n      activityId\n      fieldGoalsMade\n      fieldGoalsMissed\n      threePointersMade\n      threePointersMissed\n      freeThrows\n      missedFreeThrows\n      assists\n      steals\n      turnovers\n      offensiveRebounds\n      defensiveRebounds\n      blocks\n    }\n  }\n}": types.GetActiveAttendedMembersDocument,
    "query GetActivity($input: GetActivityInput!) {\n  getActivity(input: $input) {\n    id\n    title\n    time\n    type\n    duration\n    date\n    createdAt\n    updatedAt\n    teamId\n    attendees {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n    }\n    game {\n      activityId\n      location\n      opponentStatline {\n        activityId\n        name\n        fieldGoalsMade\n        threePointersMade\n        freeThrowsMade\n      }\n    }\n  }\n}": types.GetActivityDocument,
    "query GetGamesWithBoxScores($input: TeamStatlineInput!) {\n  getGamesWithBoxScores(input: $input) {\n    activityId\n    title\n    date\n    opponentName\n    opponentStats {\n      fieldGoalsMade\n      threePointersMade\n      freeThrowsMade\n      points\n    }\n    teamTotals {\n      fieldGoalsMade\n      threePointersMade\n      freeThrows\n      assists\n      offensiveRebounds\n      defensiveRebounds\n      steals\n      blocks\n      turnovers\n      points\n    }\n    playerStats {\n      memberId\n      name\n      fieldGoalsMade\n      threePointersMade\n      freeThrows\n      assists\n      offensiveRebounds\n      defensiveRebounds\n      steals\n      blocks\n      turnovers\n      points\n    }\n  }\n}": types.GetGamesWithBoxScoresDocument,
    "query GetStatlineAverages($input: TeamStatlineInput!) {\n  getStatlineAverages(input: $input) {\n    memberId\n    name\n    totalPoints\n    gamesPlayed\n    averages {\n      pointsPerGame\n      fieldGoalPercentage\n      threePointPercentage\n      freeThrowPercentage\n      assists\n      offensiveRebound\n      defensiveRebound\n      blocks\n      steals\n      turnovers\n    }\n  }\n}": types.GetStatlineAveragesDocument,
    "query GetStatsPerGame($input: StatsPerGameInput!) {\n  getStatsPerGame(input: $input) {\n    gameTitle\n    date\n    points\n    assists\n    rebounds\n    steals\n  }\n}": types.GetStatsPerGameDocument,
    "query GetTeamStats($input: TeamStatlineInput!) {\n  getTeamStats(input: $input) {\n    totalGames\n    totalFieldGoalsMade\n    totalFieldGoalsMissed\n    totalThreePointersMade\n    totalThreePointersMissed\n    totalFreeThrows\n    totalFreeThrowsMissed\n    totalAssists\n    totalRebounds\n    totalSteals\n    totalBlocks\n    totalTurnovers\n    totalPoints\n    totalOpponentPoints\n    averages {\n      pointsPerGame\n      fieldGoalPercentage\n      threePointPercentage\n      freeThrowPercentage\n      assists\n      rebounds\n      steals\n      blocks\n      turnovers\n    }\n    advanced {\n      offensiveRating\n      trueShootingPercentage\n      assistToTurnoverRatio\n      netRating\n      effectiveFieldGoalPercentage\n    }\n  }\n}": types.GetTeamStatsDocument,
    "query GetWeeklyTeamAverages($input: TeamStatlineInput!) {\n  getWeeklyTeamAverages(input: $input) {\n    weekStart\n    gamesPlayed\n    totalPoints\n    fieldGoalsMade\n    fieldGoalsMissed\n    threePointersMade\n    threePointersMissed\n    freeThrows\n    freeThrowsMissed\n    assists\n    rebounds\n    steals\n    blocks\n    turnovers\n    averages {\n      pointsPerGame\n      assistsPerGame\n      reboundsPerGame\n      blocksPerGame\n      stealsPerGame\n      turnoversPerGame\n    }\n  }\n}": types.GetWeeklyTeamAveragesDocument,
    "mutation SubmitStatlines($input: SubmitStatlinesInput!) {\n  submitStatlines(input: $input) {\n    success\n    count\n    opponentStatline {\n      gameId\n      name\n      fieldGoalsMade\n      threePointersMade\n      freeThrowsMade\n    }\n  }\n}": types.SubmitStatlinesDocument,
    "mutation DeleteMember($input: DeleteMemberInput!) {\n  deleteMember(input: $input)\n}": types.DeleteMemberDocument,
    "query GetMembers($input: MembersInput!) {\n  getMembers(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    attendances {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n      activity {\n        id\n        title\n        time\n        date\n      }\n    }\n    user {\n      id\n      name\n      email\n      image\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n  }\n}": types.GetMembersDocument,
    "query GetTeam($input: GetTeamInput!) {\n  getTeam(input: $input) {\n    id\n    name\n    code\n    slug\n    shortId\n    routeKey\n    image\n    ageGroup\n    creatorId\n    createdAt\n    updatedAt\n    members {\n      id\n      teamId\n      name\n      number\n      position\n      image\n      user {\n        id\n        name\n        email\n        image\n        dateOfBirth\n        phone\n        height\n        weight\n        dominantHand\n        hasOnBoarded\n      }\n    }\n  }\n}": types.GetTeamDocument,
    "query GetUserProfile($input: GetMemberProfileInput!) {\n  getUserProfile: getMemberProfile(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    user {\n      id\n      name\n      email\n      image\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    attendances {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n      activity {\n        id\n        title\n        time\n        date\n      }\n    }\n  }\n}": types.GetUserProfileDocument,
    "query GetPendingMembers($input: MembersInput!) {\n  getPendingMembers(input: $input) {\n    id\n    name\n    email\n  }\n}": types.GetPendingMembersDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetUser($teamShortId: String!) {\n  getCurrentUser(teamShortId: $teamShortId) {\n    user {\n      id\n      name\n      email\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    member {\n      id\n      userId\n      teamId\n      role\n      status\n      number\n      position\n      attendances {\n        id\n        activityId\n        memberId\n        attendanceStatus\n        reason\n        createdAt\n        updatedAt\n        activity {\n          id\n          title\n          time\n          date\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query GetUser($teamShortId: String!) {\n  getCurrentUser(teamShortId: $teamShortId) {\n    user {\n      id\n      name\n      email\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    member {\n      id\n      userId\n      teamId\n      role\n      status\n      number\n      position\n      attendances {\n        id\n        activityId\n        memberId\n        attendanceStatus\n        reason\n        createdAt\n        updatedAt\n        activity {\n          id\n          title\n          time\n          date\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation createTeam($input: CreateTeamInput!) {\n  createTeam(input: $input) {\n    id\n    name\n    image\n    ageGroup\n    code\n    creatorId\n  }\n}"): (typeof documents)["mutation createTeam($input: CreateTeamInput!) {\n  createTeam(input: $input) {\n    id\n    name\n    image\n    ageGroup\n    code\n    creatorId\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation Login($email: String!) {\n  login(email: $email) {\n    accessToken\n    refreshToken\n    hasOnBoarded\n    userId\n  }\n}\n\nmutation Refresh($refreshToken: String!) {\n  refresh(refreshToken: $refreshToken) {\n    accessToken\n    refreshToken\n    hasOnBoarded\n    userId\n  }\n}\n\nmutation Logout {\n  logout\n}"): (typeof documents)["mutation Login($email: String!) {\n  login(email: $email) {\n    accessToken\n    refreshToken\n    hasOnBoarded\n    userId\n  }\n}\n\nmutation Refresh($refreshToken: String!) {\n  refresh(refreshToken: $refreshToken) {\n    accessToken\n    refreshToken\n    hasOnBoarded\n    userId\n  }\n}\n\nmutation Logout {\n  logout\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation SubmitAttendance($input: PlayerActivityAttendanceInput!) {\n  submitAttendance(input: $input) {\n    id\n    memberId\n    attendanceStatus\n    reason\n  }\n}"): (typeof documents)["mutation SubmitAttendance($input: PlayerActivityAttendanceInput!) {\n  submitAttendance(input: $input) {\n    id\n    memberId\n    attendanceStatus\n    reason\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation AcceptTeamRequest($input: AcceptTeamRequestInput!) {\n  acceptTeamRequest(input: $input) {\n    memberId\n    teamId\n    status\n  }\n}"): (typeof documents)["mutation AcceptTeamRequest($input: AcceptTeamRequestInput!) {\n  acceptTeamRequest(input: $input) {\n    memberId\n    teamId\n    status\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation JoinTeam($input: JoinTeamInput!) {\n  joinTeam(input: $input) {\n    teamCode\n    position\n    number\n  }\n}"): (typeof documents)["mutation JoinTeam($input: JoinTeamInput!) {\n  joinTeam(input: $input) {\n    teamCode\n    position\n    number\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation RejectJoinRequest($input: TeamRequestInput!) {\n  rejectJoinRequest(input: $input) {\n    memberId\n    teamId\n    status\n  }\n}"): (typeof documents)["mutation RejectJoinRequest($input: TeamRequestInput!) {\n  rejectJoinRequest(input: $input) {\n    memberId\n    teamId\n    status\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation UpdateUser($input: UpdateUserInput!) {\n  updateUser(input: $input) {\n    name\n    dateOfBirth\n    phone\n    height\n    weight\n    dominantHand\n  }\n}"): (typeof documents)["mutation UpdateUser($input: UpdateUserInput!) {\n  updateUser(input: $input) {\n    name\n    dateOfBirth\n    phone\n    height\n    weight\n    dominantHand\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetTeamForDashboard {\n  getDashboardTeams {\n    id\n    name\n    slug\n    shortId\n    routeKey\n    ageGroup\n    members {\n      id\n    }\n    activities {\n      id\n      type\n      title\n      date\n      time\n    }\n  }\n}"): (typeof documents)["query GetTeamForDashboard {\n  getDashboardTeams {\n    id\n    name\n    slug\n    shortId\n    routeKey\n    ageGroup\n    members {\n      id\n    }\n    activities {\n      id\n      type\n      title\n      date\n      time\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateGamePlan($input: CreateGamePlanInput!) {\n  createGamePlan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"): (typeof documents)["mutation CreateGamePlan($input: CreateGamePlanInput!) {\n  createGamePlan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreatePlay($input: CreatePlayInput!) {\n  createPlay(input: $input) {\n    id\n    routeKey\n    name\n    description\n    category\n    canvas\n    createdAt\n    updatedAt\n  }\n}"): (typeof documents)["mutation CreatePlay($input: CreatePlayInput!) {\n  createPlay(input: $input) {\n    id\n    routeKey\n    name\n    description\n    category\n    canvas\n    createdAt\n    updatedAt\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreatePracticePreparation($input: CreatePracticePreparationInput!) {\n  createPracticePreparation(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"): (typeof documents)["mutation CreatePracticePreparation($input: CreatePracticePreparationInput!) {\n  createPracticePreparation(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation DeleteGamePlan($input: DeleteGamePlanInput!) {\n  deleteGamePlan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"): (typeof documents)["mutation DeleteGamePlan($input: DeleteGamePlanInput!) {\n  deleteGamePlan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation DeletePlay($input: DeletePlayInput!) {\n  deletePlay(input: $input)\n}"): (typeof documents)["mutation DeletePlay($input: DeletePlayInput!) {\n  deletePlay(input: $input)\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation DeletePracticePreparation($input: DeletePracticePreparationInput!) {\n  deletePracticePreparation(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"): (typeof documents)["mutation DeletePracticePreparation($input: DeletePracticePreparationInput!) {\n  deletePracticePreparation(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetGameplan($input: GetGamePlansInput!) {\n  getGameplan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"): (typeof documents)["query GetGameplan($input: GetGamePlansInput!) {\n  getGameplan(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetGameplanById($input: GetGamePlanByIdInput!) {\n  getGameplanById(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"): (typeof documents)["query GetGameplanById($input: GetGamePlanByIdInput!) {\n  getGameplanById(input: $input) {\n    id\n    name\n    opponent\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetGames($input: GetActivitiesInput!) {\n  getGames(input: $input) {\n    id\n    date\n    time\n    game {\n      id\n      title\n      date\n      time\n      activityId\n      location\n      opponentStatline {\n        activityId\n        name\n        fieldGoalsMade\n        threePointersMade\n        freeThrowsMade\n      }\n    }\n  }\n}"): (typeof documents)["query GetGames($input: GetActivitiesInput!) {\n  getGames(input: $input) {\n    id\n    date\n    time\n    game {\n      id\n      title\n      date\n      time\n      activityId\n      location\n      opponentStatline {\n        activityId\n        name\n        fieldGoalsMade\n        threePointersMade\n        freeThrowsMade\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetPlay($input: GetPlayInput!) {\n  getPlay(input: $input) {\n    id\n    routeKey\n    name\n    category\n    description\n    canvas\n    createdAt\n    updatedAt\n  }\n}"): (typeof documents)["query GetPlay($input: GetPlayInput!) {\n  getPlay(input: $input) {\n    id\n    routeKey\n    name\n    category\n    description\n    canvas\n    createdAt\n    updatedAt\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetPlays($input: GetPlaysInput!) {\n  getPlays(input: $input) {\n    id\n    routeKey\n    name\n    category\n    description\n    canvas\n    createdAt\n    updatedAt\n  }\n}"): (typeof documents)["query GetPlays($input: GetPlaysInput!) {\n  getPlays(input: $input) {\n    id\n    routeKey\n    name\n    category\n    description\n    canvas\n    createdAt\n    updatedAt\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetPracticePreparationById($input: GetPracticePreparationByIdInput!) {\n  getPracticePreparationById(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"): (typeof documents)["query GetPracticePreparationById($input: GetPracticePreparationByIdInput!) {\n  getPracticePreparationById(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetPracticePreparations($input: GetPracticePreparationsInput!) {\n  getPracticePreparations(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"): (typeof documents)["query GetPracticePreparations($input: GetPracticePreparationsInput!) {\n  getPracticePreparations(input: $input) {\n    id\n    name\n    focus\n    notes\n    activityId\n    teamId\n    createdAt\n    updatedAt\n    activity {\n      id\n      title\n      date\n      time\n    }\n    plays {\n      id\n      name\n      category\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetPractices($input: GetActivitiesInput!) {\n  getPractices(input: $input) {\n    practice {\n      id\n      title\n      date\n      time\n      activityId\n      facility\n      practicetype\n    }\n  }\n}"): (typeof documents)["query GetPractices($input: GetActivitiesInput!) {\n  getPractices(input: $input) {\n    practice {\n      id\n      title\n      date\n      time\n      activityId\n      facility\n      practicetype\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetTeamActivities($routeKey: String!) {\n  getTeamActivities(routeKey: $routeKey) {\n    id\n    name\n    code\n    slug\n    routeKey\n    shortId\n    image\n    ageGroup\n    createdAt\n    updatedAt\n    creatorId\n    members {\n      id\n      name\n      image\n      teamId\n      userId\n    }\n    activities {\n      id\n      teamId\n      type\n      title\n      time\n      duration\n      date\n      createdAt\n      updatedAt\n      attendees {\n        id\n        activityId\n        memberId\n        attendanceStatus\n        reason\n        createdAt\n        updatedAt\n      }\n    }\n  }\n}"): (typeof documents)["query GetTeamActivities($routeKey: String!) {\n  getTeamActivities(routeKey: $routeKey) {\n    id\n    name\n    code\n    slug\n    routeKey\n    shortId\n    image\n    ageGroup\n    createdAt\n    updatedAt\n    creatorId\n    members {\n      id\n      name\n      image\n      teamId\n      userId\n    }\n    activities {\n      id\n      teamId\n      type\n      title\n      time\n      duration\n      date\n      createdAt\n      updatedAt\n      attendees {\n        id\n        activityId\n        memberId\n        attendanceStatus\n        reason\n        createdAt\n        updatedAt\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateFeedback($input: CreateFeedbackInput!) {\n  createFeedback(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    feedback {\n      notes\n      coach\n    }\n  }\n}"): (typeof documents)["mutation CreateFeedback($input: CreateFeedbackInput!) {\n  createFeedback(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    feedback {\n      notes\n      coach\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateFilm($input: CreateFilmInput!) {\n  createFilm(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    film {\n      notes\n    }\n  }\n}"): (typeof documents)["mutation CreateFilm($input: CreateFilmInput!) {\n  createFilm(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    film {\n      notes\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateGame($input: CreateGameInput!) {\n  createGame(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    game {\n      location\n    }\n  }\n}"): (typeof documents)["mutation CreateGame($input: CreateGameInput!) {\n  createGame(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    game {\n      location\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateMeeting($input: CreateMeetingInput!) {\n  createMeeting(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    meeting {\n      notes\n    }\n  }\n}"): (typeof documents)["mutation CreateMeeting($input: CreateMeetingInput!) {\n  createMeeting(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    meeting {\n      notes\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreatePractice($input: CreatePracticeInput!) {\n  createPractice(input: $input) {\n    title\n    time\n    date\n    duration\n    type\n    practice {\n      facility\n      practicetype\n    }\n  }\n}"): (typeof documents)["mutation CreatePractice($input: CreatePracticeInput!) {\n  createPractice(input: $input) {\n    title\n    time\n    date\n    duration\n    type\n    practice {\n      facility\n      practicetype\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation DeleteActivity($input: DeleteActivity!) {\n  deleteActivity(input: $input) {\n    id\n  }\n}"): (typeof documents)["mutation DeleteActivity($input: DeleteActivity!) {\n  deleteActivity(input: $input) {\n    id\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation UpdateFeedback($input: UpdateFeedbackInput!) {\n  updateFeedback(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    teamId\n    feedback {\n      notes\n      coach\n    }\n  }\n}"): (typeof documents)["mutation UpdateFeedback($input: UpdateFeedbackInput!) {\n  updateFeedback(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    teamId\n    feedback {\n      notes\n      coach\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation UpdateFilm($input: UpdateFilmInput!) {\n  updateFilm(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    teamId\n    film {\n      notes\n    }\n  }\n}"): (typeof documents)["mutation UpdateFilm($input: UpdateFilmInput!) {\n  updateFilm(input: $input) {\n    id\n    title\n    time\n    date\n    type\n    teamId\n    film {\n      notes\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation UpdateGame($input: UpdateGameInput!) {\n  updateGame(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    game {\n      location\n    }\n  }\n}"): (typeof documents)["mutation UpdateGame($input: UpdateGameInput!) {\n  updateGame(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    game {\n      location\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation UpdateMeeting($input: UpdateMeetingInput!) {\n  updateMeeting(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    meeting {\n      notes\n    }\n  }\n}"): (typeof documents)["mutation UpdateMeeting($input: UpdateMeetingInput!) {\n  updateMeeting(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    meeting {\n      notes\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation UpdatePractice($input: UpdatePracticeInput!) {\n  updatePractice(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    practice {\n      facility\n      practicetype\n    }\n  }\n}"): (typeof documents)["mutation UpdatePractice($input: UpdatePracticeInput!) {\n  updatePractice(input: $input) {\n    id\n    title\n    time\n    date\n    duration\n    type\n    teamId\n    practice {\n      facility\n      practicetype\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetActiveAttendedMembers($input: ActiveAttendedMembersInput!) {\n  getActiveAttendedMembers(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    user {\n      id\n      name\n      image\n      email\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    statlines {\n      id\n      activityId\n      fieldGoalsMade\n      fieldGoalsMissed\n      threePointersMade\n      threePointersMissed\n      freeThrows\n      missedFreeThrows\n      assists\n      steals\n      turnovers\n      offensiveRebounds\n      defensiveRebounds\n      blocks\n    }\n  }\n}"): (typeof documents)["query GetActiveAttendedMembers($input: ActiveAttendedMembersInput!) {\n  getActiveAttendedMembers(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    user {\n      id\n      name\n      image\n      email\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    statlines {\n      id\n      activityId\n      fieldGoalsMade\n      fieldGoalsMissed\n      threePointersMade\n      threePointersMissed\n      freeThrows\n      missedFreeThrows\n      assists\n      steals\n      turnovers\n      offensiveRebounds\n      defensiveRebounds\n      blocks\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetActivity($input: GetActivityInput!) {\n  getActivity(input: $input) {\n    id\n    title\n    time\n    type\n    duration\n    date\n    createdAt\n    updatedAt\n    teamId\n    attendees {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n    }\n    game {\n      activityId\n      location\n      opponentStatline {\n        activityId\n        name\n        fieldGoalsMade\n        threePointersMade\n        freeThrowsMade\n      }\n    }\n  }\n}"): (typeof documents)["query GetActivity($input: GetActivityInput!) {\n  getActivity(input: $input) {\n    id\n    title\n    time\n    type\n    duration\n    date\n    createdAt\n    updatedAt\n    teamId\n    attendees {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n    }\n    game {\n      activityId\n      location\n      opponentStatline {\n        activityId\n        name\n        fieldGoalsMade\n        threePointersMade\n        freeThrowsMade\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetGamesWithBoxScores($input: TeamStatlineInput!) {\n  getGamesWithBoxScores(input: $input) {\n    activityId\n    title\n    date\n    opponentName\n    opponentStats {\n      fieldGoalsMade\n      threePointersMade\n      freeThrowsMade\n      points\n    }\n    teamTotals {\n      fieldGoalsMade\n      threePointersMade\n      freeThrows\n      assists\n      offensiveRebounds\n      defensiveRebounds\n      steals\n      blocks\n      turnovers\n      points\n    }\n    playerStats {\n      memberId\n      name\n      fieldGoalsMade\n      threePointersMade\n      freeThrows\n      assists\n      offensiveRebounds\n      defensiveRebounds\n      steals\n      blocks\n      turnovers\n      points\n    }\n  }\n}"): (typeof documents)["query GetGamesWithBoxScores($input: TeamStatlineInput!) {\n  getGamesWithBoxScores(input: $input) {\n    activityId\n    title\n    date\n    opponentName\n    opponentStats {\n      fieldGoalsMade\n      threePointersMade\n      freeThrowsMade\n      points\n    }\n    teamTotals {\n      fieldGoalsMade\n      threePointersMade\n      freeThrows\n      assists\n      offensiveRebounds\n      defensiveRebounds\n      steals\n      blocks\n      turnovers\n      points\n    }\n    playerStats {\n      memberId\n      name\n      fieldGoalsMade\n      threePointersMade\n      freeThrows\n      assists\n      offensiveRebounds\n      defensiveRebounds\n      steals\n      blocks\n      turnovers\n      points\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetStatlineAverages($input: TeamStatlineInput!) {\n  getStatlineAverages(input: $input) {\n    memberId\n    name\n    totalPoints\n    gamesPlayed\n    averages {\n      pointsPerGame\n      fieldGoalPercentage\n      threePointPercentage\n      freeThrowPercentage\n      assists\n      offensiveRebound\n      defensiveRebound\n      blocks\n      steals\n      turnovers\n    }\n  }\n}"): (typeof documents)["query GetStatlineAverages($input: TeamStatlineInput!) {\n  getStatlineAverages(input: $input) {\n    memberId\n    name\n    totalPoints\n    gamesPlayed\n    averages {\n      pointsPerGame\n      fieldGoalPercentage\n      threePointPercentage\n      freeThrowPercentage\n      assists\n      offensiveRebound\n      defensiveRebound\n      blocks\n      steals\n      turnovers\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetStatsPerGame($input: StatsPerGameInput!) {\n  getStatsPerGame(input: $input) {\n    gameTitle\n    date\n    points\n    assists\n    rebounds\n    steals\n  }\n}"): (typeof documents)["query GetStatsPerGame($input: StatsPerGameInput!) {\n  getStatsPerGame(input: $input) {\n    gameTitle\n    date\n    points\n    assists\n    rebounds\n    steals\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetTeamStats($input: TeamStatlineInput!) {\n  getTeamStats(input: $input) {\n    totalGames\n    totalFieldGoalsMade\n    totalFieldGoalsMissed\n    totalThreePointersMade\n    totalThreePointersMissed\n    totalFreeThrows\n    totalFreeThrowsMissed\n    totalAssists\n    totalRebounds\n    totalSteals\n    totalBlocks\n    totalTurnovers\n    totalPoints\n    totalOpponentPoints\n    averages {\n      pointsPerGame\n      fieldGoalPercentage\n      threePointPercentage\n      freeThrowPercentage\n      assists\n      rebounds\n      steals\n      blocks\n      turnovers\n    }\n    advanced {\n      offensiveRating\n      trueShootingPercentage\n      assistToTurnoverRatio\n      netRating\n      effectiveFieldGoalPercentage\n    }\n  }\n}"): (typeof documents)["query GetTeamStats($input: TeamStatlineInput!) {\n  getTeamStats(input: $input) {\n    totalGames\n    totalFieldGoalsMade\n    totalFieldGoalsMissed\n    totalThreePointersMade\n    totalThreePointersMissed\n    totalFreeThrows\n    totalFreeThrowsMissed\n    totalAssists\n    totalRebounds\n    totalSteals\n    totalBlocks\n    totalTurnovers\n    totalPoints\n    totalOpponentPoints\n    averages {\n      pointsPerGame\n      fieldGoalPercentage\n      threePointPercentage\n      freeThrowPercentage\n      assists\n      rebounds\n      steals\n      blocks\n      turnovers\n    }\n    advanced {\n      offensiveRating\n      trueShootingPercentage\n      assistToTurnoverRatio\n      netRating\n      effectiveFieldGoalPercentage\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetWeeklyTeamAverages($input: TeamStatlineInput!) {\n  getWeeklyTeamAverages(input: $input) {\n    weekStart\n    gamesPlayed\n    totalPoints\n    fieldGoalsMade\n    fieldGoalsMissed\n    threePointersMade\n    threePointersMissed\n    freeThrows\n    freeThrowsMissed\n    assists\n    rebounds\n    steals\n    blocks\n    turnovers\n    averages {\n      pointsPerGame\n      assistsPerGame\n      reboundsPerGame\n      blocksPerGame\n      stealsPerGame\n      turnoversPerGame\n    }\n  }\n}"): (typeof documents)["query GetWeeklyTeamAverages($input: TeamStatlineInput!) {\n  getWeeklyTeamAverages(input: $input) {\n    weekStart\n    gamesPlayed\n    totalPoints\n    fieldGoalsMade\n    fieldGoalsMissed\n    threePointersMade\n    threePointersMissed\n    freeThrows\n    freeThrowsMissed\n    assists\n    rebounds\n    steals\n    blocks\n    turnovers\n    averages {\n      pointsPerGame\n      assistsPerGame\n      reboundsPerGame\n      blocksPerGame\n      stealsPerGame\n      turnoversPerGame\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation SubmitStatlines($input: SubmitStatlinesInput!) {\n  submitStatlines(input: $input) {\n    success\n    count\n    opponentStatline {\n      gameId\n      name\n      fieldGoalsMade\n      threePointersMade\n      freeThrowsMade\n    }\n  }\n}"): (typeof documents)["mutation SubmitStatlines($input: SubmitStatlinesInput!) {\n  submitStatlines(input: $input) {\n    success\n    count\n    opponentStatline {\n      gameId\n      name\n      fieldGoalsMade\n      threePointersMade\n      freeThrowsMade\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation DeleteMember($input: DeleteMemberInput!) {\n  deleteMember(input: $input)\n}"): (typeof documents)["mutation DeleteMember($input: DeleteMemberInput!) {\n  deleteMember(input: $input)\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetMembers($input: MembersInput!) {\n  getMembers(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    attendances {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n      activity {\n        id\n        title\n        time\n        date\n      }\n    }\n    user {\n      id\n      name\n      email\n      image\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n  }\n}"): (typeof documents)["query GetMembers($input: MembersInput!) {\n  getMembers(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    attendances {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n      activity {\n        id\n        title\n        time\n        date\n      }\n    }\n    user {\n      id\n      name\n      email\n      image\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetTeam($input: GetTeamInput!) {\n  getTeam(input: $input) {\n    id\n    name\n    code\n    slug\n    shortId\n    routeKey\n    image\n    ageGroup\n    creatorId\n    createdAt\n    updatedAt\n    members {\n      id\n      teamId\n      name\n      number\n      position\n      image\n      user {\n        id\n        name\n        email\n        image\n        dateOfBirth\n        phone\n        height\n        weight\n        dominantHand\n        hasOnBoarded\n      }\n    }\n  }\n}"): (typeof documents)["query GetTeam($input: GetTeamInput!) {\n  getTeam(input: $input) {\n    id\n    name\n    code\n    slug\n    shortId\n    routeKey\n    image\n    ageGroup\n    creatorId\n    createdAt\n    updatedAt\n    members {\n      id\n      teamId\n      name\n      number\n      position\n      image\n      user {\n        id\n        name\n        email\n        image\n        dateOfBirth\n        phone\n        height\n        weight\n        dominantHand\n        hasOnBoarded\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetUserProfile($input: GetMemberProfileInput!) {\n  getUserProfile: getMemberProfile(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    user {\n      id\n      name\n      email\n      image\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    attendances {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n      activity {\n        id\n        title\n        time\n        date\n      }\n    }\n  }\n}"): (typeof documents)["query GetUserProfile($input: GetMemberProfileInput!) {\n  getUserProfile: getMemberProfile(input: $input) {\n    id\n    userId\n    teamId\n    role\n    status\n    number\n    position\n    name\n    user {\n      id\n      name\n      email\n      image\n      dateOfBirth\n      phone\n      height\n      weight\n      dominantHand\n      hasOnBoarded\n    }\n    attendances {\n      id\n      activityId\n      memberId\n      attendanceStatus\n      reason\n      createdAt\n      updatedAt\n      activity {\n        id\n        title\n        time\n        date\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetPendingMembers($input: MembersInput!) {\n  getPendingMembers(input: $input) {\n    id\n    name\n    email\n  }\n}"): (typeof documents)["query GetPendingMembers($input: MembersInput!) {\n  getPendingMembers(input: $input) {\n    id\n    name\n    email\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;