query GetUser($teamShortId: String!) {
  getCurrentUser(teamShortId: $teamShortId) {
    user {
      id
      name
      email
      dateOfBirth
      phone
      height
      weight
      dominantHand
      hasOnBoarded
    }
    member {
      id
      userId
      teamId
      role
      status
      number
      position
      attendances {
        id
        activityId
        memberId
        attendanceStatus
        reason
        createdAt
        updatedAt
        activity {
          id
          title
          time
          date
        }
      }
    }
  }
}
