query GetActivity($input: GetActivityInput!) {
  getActivity(input: $input) {
    id
    title
    time
    type
    duration
    date
    createdAt
    updatedAt
    teamId
    attendees {
      id
      activityId
      memberId
      attendanceStatus
      reason
      createdAt
      updatedAt
    }
    game {
      activityId
      location
      opponentStatline {
        activityId
        name
        fieldGoalsMade
        threePointersMade
        freeThrowsMade
      }
    }
  }
}
