query GetGamesWithBoxScores($input: TeamStatlineInput!) {
  getGamesWithBoxScores(input: $input) {
    activityId
    title
    date
    opponentName
    opponentStats {
      fieldGoalsMade
      threePointersMade
      freeThrowsMade
      points
    }
    teamTotals {
      fieldGoalsMade
      threePointersMade
      freeThrows
      assists
      offensiveRebounds
      defensiveRebounds
      steals
      blocks
      turnovers
      points
    }
    playerStats {
      memberId
      name
      fieldGoalsMade
      threePointersMade
      freeThrows
      assists
      offensiveRebounds
      defensiveRebounds
      steals
      blocks
      turnovers
      points
    }
  }
}
