mutation SubmitStatlines($input: SubmitStatlinesInput!) {
  submitStatlines(input: $input) {
    success
    count
    opponentStatline {
      gameId
      name
      fieldGoalsMade
      threePointersMade
      freeThrowsMade
    }
  }
}
