query GetTeamForDashboard {
  getDashboardTeams {
    id
    name
    slug
    shortId
    routeKey
    ageGroup
    members {
      id
    }
    activities {
      id
      type
      title
      date
      time
    }
  }
}
