mutation CreatePracticePreparation($input: CreatePracticePreparationInput!) {
  createPracticePreparation(input: $input) {
    id
    name
    focus
    notes
    activityId
    teamId
    createdAt
    updatedAt
    activity {
      id
      title
      date
      time
    }
    plays {
      id
      name
      category
    }
  }
}
